import express from 'express';
import path from 'path';
import fs from 'fs';
import crypto from 'crypto';
import dotenv from 'dotenv';
import { createClient, SupabaseClient } from '@supabase/supabase-js';
import { createServer as createViteServer } from 'vite';

dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json());

// Lazy Supabase client initialization (using service role key on server)
let supabaseClient: SupabaseClient | null = null;

function getSupabaseClient(): SupabaseClient | null {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!url || !key) {
    return null;
  }

  if (!supabaseClient) {
    try {
      supabaseClient = createClient(url, key, {
        auth: {
          persistSession: false,
          autoRefreshToken: false,
        },
      });
    } catch (err) {
      console.error('Error initializing Supabase client:', err);
      return null;
    }
  }

  return supabaseClient;
}

function isValidUuid(id?: string): boolean {
  if (!id) return false;
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id);
}

function ensureUuid(id?: string): string {
  if (id && isValidUuid(id)) return id;
  if (id && id.trim()) {
    // Generate deterministic UUIDv4-like string from arbitrary string identifier
    const hash = crypto.createHash('sha256').update(id.trim()).digest('hex');
    return `${hash.slice(0, 8)}-${hash.slice(8, 12)}-4${hash.slice(13, 16)}-a${hash.slice(17, 20)}-${hash.slice(20, 32)}`;
  }
  return crypto.randomUUID();
}

// -------------------------------------------------------------
// Complete PostgreSQL Database Schema (4 Tables)
// -------------------------------------------------------------
const SQL_SCHEMA = `-- =============================================================
-- Cyberwrap & Analytics Supabase Database Schema
-- Run this in your Supabase SQL Editor
-- =============================================================

-- Enable pgcrypto extension for UUID generation
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 1. analytics_events
CREATE TABLE IF NOT EXISTS public.analytics_events (
  id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id text NOT NULL,
  campaign text NOT NULL DEFAULT 'Summer Shawarma Splash',
  event text NOT NULL,
  timestamp int8 NOT NULL,
  game_version text NOT NULL DEFAULT 'v1.4.2',
  data jsonb DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  player_id uuid NULL,
  game_mode text NULL,
  visitor_id text NULL,
  event_category text NULL,
  source text NULL,
  medium text NULL,
  referrer text NULL,
  page text NULL,
  path text NULL
);

-- 2. analytics_visitors
CREATE TABLE IF NOT EXISTS public.analytics_visitors (
  visitor_id text PRIMARY KEY,
  first_seen_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  first_source text NULL,
  first_medium text NULL,
  first_campaign text NULL,
  first_referrer text NULL,
  first_landing_page text NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 3. analytics_sessions
CREATE TABLE IF NOT EXISTS public.analytics_sessions (
  session_id text PRIMARY KEY,
  visitor_id text NOT NULL,
  started_at timestamptz NOT NULL DEFAULT now(),
  ended_at timestamptz NULL,
  landing_page text NULL,
  source text NULL,
  medium text NULL,
  campaign text NULL,
  referrer text NULL,
  device_type text NULL,
  browser text NULL,
  os text NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 4. cyberwrap_rewards
CREATE TABLE IF NOT EXISTS public.cyberwrap_rewards (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  player_id uuid NOT NULL UNIQUE,
  cumulative_score int4 NOT NULL DEFAULT 0,
  cycle_started_at timestamptz NOT NULL DEFAULT now(),
  cycle_expires_at timestamptz NOT NULL DEFAULT (now() + interval '7 days'),
  coupons_earned_in_cycle int4 NOT NULL DEFAULT 0,
  reward_status text NOT NULL DEFAULT 'in_progress',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- 5. cyberwrap_coupons
CREATE TABLE IF NOT EXISTS public.cyberwrap_coupons (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  player_id uuid NOT NULL,
  reward_id uuid NOT NULL REFERENCES public.cyberwrap_rewards(id) ON DELETE CASCADE,
  code_hash text NOT NULL UNIQUE,
  discount_percent int4 NOT NULL DEFAULT 20,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'redeemed', 'expired')),
  generated_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL DEFAULT (now() + interval '7 days'),
  redeemed_at timestamptz NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- 6. cyberwrap_reward_claims
CREATE TABLE IF NOT EXISTS public.cyberwrap_reward_claims (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  player_id uuid NOT NULL,
  session_id text NOT NULL,
  game_id uuid NOT NULL DEFAULT gen_random_uuid(),
  score_amount int4 NOT NULL,
  credited_amount int4 NOT NULL,
  coupon_id uuid NULL REFERENCES public.cyberwrap_coupons(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- Indexes for lightning fast queries
CREATE INDEX IF NOT EXISTS idx_analytics_events_created ON public.analytics_events(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_analytics_events_event ON public.analytics_events(event);
CREATE INDEX IF NOT EXISTS idx_analytics_events_visitor ON public.analytics_events(visitor_id);
CREATE INDEX IF NOT EXISTS idx_analytics_events_category ON public.analytics_events(event_category);
CREATE INDEX IF NOT EXISTS idx_analytics_events_source ON public.analytics_events(source);
CREATE INDEX IF NOT EXISTS idx_coupons_status ON public.cyberwrap_coupons(status);
CREATE INDEX IF NOT EXISTS idx_coupons_code ON public.cyberwrap_coupons(code_hash);
CREATE INDEX IF NOT EXISTS idx_claims_player ON public.cyberwrap_reward_claims(player_id);
CREATE INDEX IF NOT EXISTS idx_claims_game_id ON public.cyberwrap_reward_claims(game_id);

-- Enable Row Level Security (RLS)
ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analytics_visitors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analytics_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cyberwrap_rewards ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cyberwrap_coupons ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cyberwrap_reward_claims ENABLE ROW LEVEL SECURITY;

-- Allow Public anonymous inserts for analytics and claims via APIs
CREATE POLICY "Allow public insert analytics" ON public.analytics_events FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public read analytics" ON public.analytics_events FOR SELECT USING (true);
CREATE POLICY "Allow public insert visitors" ON public.analytics_visitors FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update visitors" ON public.analytics_visitors FOR UPDATE USING (true);
CREATE POLICY "Allow public read visitors" ON public.analytics_visitors FOR SELECT USING (true);
CREATE POLICY "Allow public insert sessions" ON public.analytics_sessions FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update sessions" ON public.analytics_sessions FOR UPDATE USING (true);
CREATE POLICY "Allow public read sessions" ON public.analytics_sessions FOR SELECT USING (true);
CREATE POLICY "Allow public read rewards" ON public.cyberwrap_rewards FOR SELECT USING (true);
CREATE POLICY "Allow public read coupons" ON public.cyberwrap_coupons FOR SELECT USING (true);
CREATE POLICY "Allow public read claims" ON public.cyberwrap_reward_claims FOR SELECT USING (true);
`;

// -------------------------------------------------------------
// In-Memory Fallback Store & Demo Seed Data
// -------------------------------------------------------------
const CAMPAIGNS = [
  'Summer Shawarma Splash',
  'Student Special Buea',
  'Weekend Feast Bokwaongo',
  'Zobo Loyalty Blast',
  'Independence Promo'
];

interface AnalyticsRow {
  id: number | string;
  session_id: string;
  campaign: string;
  event: string;
  timestamp: number;
  game_version?: string | null;
  game_mode?: string | null;
  data: Record<string, any>;
  created_at: string;
  player_id?: string | null;
  visitor_id?: string | null;
  event_category?: string | null;
  source?: string | null;
  medium?: string | null;
  referrer?: string | null;
  page?: string | null;
  path?: string | null;
}

interface VisitorRecord {
  visitor_id: string;
  first_seen_at: string;
  last_seen_at: string;
  first_source?: string | null;
  first_medium?: string | null;
  first_campaign?: string | null;
  first_referrer?: string | null;
  first_landing_page?: string | null;
  created_at: string;
}

interface SessionRecord {
  session_id: string;
  visitor_id: string;
  started_at: string;
  ended_at?: string | null;
  landing_page?: string | null;
  source?: string | null;
  medium?: string | null;
  campaign?: string | null;
  referrer?: string | null;
  device_type?: string | null;
  browser?: string | null;
  os?: string | null;
  created_at: string;
}

const inMemoryVisitors = new Map<string, VisitorRecord>();
const inMemorySessions = new Map<string, SessionRecord>();

interface CyberwrapRewardRow {
  id: string;
  player_id: string;
  playerName?: string;
  cumulative_score: number;
  cycle_started_at: string;
  cycle_expires_at: string;
  coupons_earned_in_cycle: number;
  reward_status: string;
  created_at: string;
  updated_at: string;
}

interface CyberwrapCouponRow {
  id: string;
  player_id: string;
  reward_id: string;
  code_hash: string;
  discount_percent: number;
  status: 'active' | 'redeemed' | 'expired';
  generated_at: string;
  expires_at: string;
  redeemed_at?: string | null;
  created_at: string;
}

interface CyberwrapRewardClaimRow {
  id: string;
  player_id: string;
  session_id: string;
  game_id: string;
  score_amount: number;
  credited_amount: number;
  coupon_id?: string | null;
  created_at: string;
}

// Fallback in-memory state initialized empty - only populated during explicit client test operations
let inMemoryEvents: AnalyticsRow[] = [];
let inMemoryPlayers: CyberwrapRewardRow[] = [];
let inMemoryCoupons: CyberwrapCouponRow[] = [];
let inMemoryClaims: CyberwrapRewardClaimRow[] = [];

// -------------------------------------------------------------
// Analytics Aggregation Engine
// -------------------------------------------------------------
function computeAnalyticsSummary(rawEvents: AnalyticsRow[]) {
  const totalEvents = rawEvents.length;
  const uniqueSessions = new Set(rawEvents.map(e => e.session_id)).size;
  
  // Unique visitors: count distinct visitor_id, fallback to uniqueSessions if none
  const visitorIds = new Set(rawEvents.filter(e => e.visitor_id).map(e => e.visitor_id as string));
  const uniqueVisitors = visitorIds.size > 0 ? visitorIds.size : uniqueSessions;

  // Website KPIs
  const pageViews = rawEvents.filter(e => e.event === 'page_viewed' || e.event === 'landing_page_viewed').length;
  const menuViews = rawEvents.filter(e => e.event === 'menu_viewed').length;
  const orderIntentCount = rawEvents.filter(e => e.event === 'order_cta_clicked' || e.event === 'order_initiated').length;
  const whatsappOrderOpened = rawEvents.filter(e => e.event === 'whatsapp_order_opened').length;
  const conversionToWhatsAppIntent = uniqueSessions > 0 
    ? Number(((orderIntentCount / uniqueSessions) * 100).toFixed(1)) 
    : 0;

  const websiteKPIs = {
    uniqueVisitors,
    totalSessions: uniqueSessions,
    pageViews,
    menuViews,
    orderIntentCount,
    whatsappOrderOpened,
    conversionToWhatsAppIntent
  };

  // Daily Run KPIs
  const dailyRunEventsList = ['game_started', 'game_played', 'challenge_completed', 'game_completed', 'daily_run_cta_clicked', 'post_order_daily_run_cta_clicked', 'daily_run_section_viewed', 'cyberwrap_launch_clicked'];
  const dailyRunIdentities = new Set(
    rawEvents
      .filter(e => dailyRunEventsList.includes(e.event))
      .map(e => e.player_id || e.visitor_id || e.session_id)
  );
  const dailyRunVisitors = dailyRunIdentities.size;
  const dailyRunStarts = rawEvents.filter(e => ['game_started', 'game_played', 'cyberwrap_launch_clicked'].includes(e.event)).length;
  const dailyRunCompletions = rawEvents.filter(e => ['challenge_completed', 'game_completed'].includes(e.event)).length;
  const rewardsEarned = rawEvents.filter(e => ['coupon_earned', 'reward_earned'].includes(e.event)).length;
  const couponsRedeemed = rawEvents.filter(e => e.event === 'coupon_redeemed').length;

  const dailyRunKPIs = {
    dailyRunVisitors,
    dailyRunStarts,
    dailyRunCompletions,
    rewardsEarned,
    couponsRedeemed
  };

  // Cross-Journey KPIs
  // Identify sessions/visitors with daily run interaction
  const dailyRunUsers = new Set<string>();
  rawEvents.forEach(e => {
    if (dailyRunEventsList.includes(e.event)) {
      if (e.visitor_id) dailyRunUsers.add(e.visitor_id);
      if (e.session_id) dailyRunUsers.add(e.session_id);
      if (e.player_id) dailyRunUsers.add(e.player_id);
    }
  });

  let dailyRunToWhatsAppIntent = 0;
  let nonDailyRunToWhatsAppIntent = 0;
  let couponAssistedOrderIntent = 0;

  rawEvents.forEach(e => {
    if (e.event === 'order_cta_clicked' || e.event === 'order_initiated' || e.event === 'whatsapp_order_opened') {
      const isDailyRun = (e.visitor_id && dailyRunUsers.has(e.visitor_id)) ||
                         (e.session_id && dailyRunUsers.has(e.session_id)) ||
                         (e.player_id && dailyRunUsers.has(e.player_id));
      if (isDailyRun) {
        dailyRunToWhatsAppIntent++;
      } else {
        nonDailyRunToWhatsAppIntent++;
      }

      if (e.data && (e.data.coupon_applied || e.data.coupon_id || e.data.discount_xaf > 0)) {
        couponAssistedOrderIntent++;
      }
    }
  });

  const postOrderDailyRunStarts = rawEvents.filter(e => e.event === 'post_order_daily_run_cta_clicked').length;

  const crossJourneyKPIs = {
    dailyRunToWhatsAppIntent,
    nonDailyRunToWhatsAppIntent,
    postOrderDailyRunStarts,
    couponAssistedOrderIntent
  };

  // Source Performance (13 required properties)
  const defaultSources = ['website', 'instagram', 'qr_table', 'qr_counter', 'qr_receipt', 'qr_delivery', 'social', 'direct', 'other'];
  const allSources = Array.from(new Set([
    ...defaultSources,
    ...rawEvents.map(e => e.source || (e.data && e.data.source) || 'website')
  ]));

  const sourcePerformance = allSources.map(srcKey => {
    const srcEvents = rawEvents.filter(e => {
      const s = e.source || (e.data && e.data.source) || 'website';
      return s === srcKey;
    });

    const srcVisitors = new Set(srcEvents.filter(e => e.visitor_id).map(e => e.visitor_id as string)).size ||
                         new Set(srcEvents.map(e => e.session_id)).size;
    const srcSessions = new Set(srcEvents.map(e => e.session_id)).size;
    const srcPlayers = new Set(srcEvents.filter(e => e.player_id).map(e => e.player_id as string)).size;

    const gameStarts = srcEvents.filter(e => ['game_started', 'game_played', 'cyberwrap_launch_clicked'].includes(e.event)).length;
    const challengesCompleted = srcEvents.filter(e => ['challenge_completed', 'game_completed'].includes(e.event)).length;
    const couponsEarned = srcEvents.filter(e => ['coupon_earned', 'reward_earned'].includes(e.event)).length;
    const srcCouponsRedeemed = srcEvents.filter(e => e.event === 'coupon_redeemed').length;
    const srcMenuViews = srcEvents.filter(e => e.event === 'menu_viewed').length;
    const srcOrderIntentCount = srcEvents.filter(e => e.event === 'order_cta_clicked' || e.event === 'order_initiated').length;
    const srcWhatsAppOpened = srcEvents.filter(e => e.event === 'whatsapp_order_opened').length;
    const conversion = srcSessions > 0 ? Number(((srcOrderIntentCount / srcSessions) * 100).toFixed(1)) : 0;

    const displayNames: Record<string, string> = {
      website: 'Website (Direct/Organic)',
      instagram: 'Instagram Bio/Stories',
      qr_table: 'Table QR Stand',
      qr_counter: 'Checkout Counter QR',
      qr_receipt: 'Receipt QR Code',
      qr_delivery: 'Takeout Bag Sticker',
      social: 'Social Media',
      direct: 'Direct Link',
      other: 'Other Sources'
    };

    return {
      source: srcKey,
      displayName: displayNames[srcKey] || srcKey.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase()),
      visitors: srcVisitors,
      sessions: srcSessions,
      players: srcPlayers,
      gameStarts,
      challengesCompleted,
      couponsEarned,
      couponsRedeemed: srcCouponsRedeemed,
      menuViews: srcMenuViews,
      orderIntentCount: srcOrderIntentCount,
      whatsappOrderOpened: srcWhatsAppOpened,
      conversionToWhatsAppIntent: conversion,
      ordersInitiated: srcOrderIntentCount // legacy alias
    };
  }).filter(sp => sp.sessions > 0 || defaultSources.includes(sp.source));

  // Legacy event frequency
  const eventCounts: Record<string, number> = {};
  rawEvents.forEach(e => {
    eventCounts[e.event] = (eventCounts[e.event] || 0) + 1;
  });

  const eventFrequency = Object.entries(eventCounts).map(([event, count]) => ({
    event,
    displayName: event.replace(/_/g, ' ').replace(/\b\w/g, l => l.toUpperCase()),
    count,
    percentage: totalEvents > 0 ? Math.round((count / totalEvents) * 100) : 0
  })).sort((a, b) => b.count - a.count);

  // Volume over time
  const volumeMap: Record<string, { total: number; games: number; couponsEarned: number; couponsRedeemed: number }> = {};
  const chronoEvents = [...rawEvents].sort((a, b) => new Date(a.created_at).getTime() - new Date(b.created_at).getTime());

  chronoEvents.forEach(e => {
    const d = new Date(e.created_at);
    const key = d.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
    if (!volumeMap[key]) {
      volumeMap[key] = { total: 0, games: 0, couponsEarned: 0, couponsRedeemed: 0 };
    }
    volumeMap[key].total++;
    if (['game_played', 'game_started', 'cyberwrap_launch_clicked'].includes(e.event)) volumeMap[key].games++;
    if (['coupon_earned', 'reward_earned'].includes(e.event)) volumeMap[key].couponsEarned++;
    if (e.event === 'coupon_redeemed') volumeMap[key].couponsRedeemed++;
  });

  const volumeOverTime = Object.entries(volumeMap).map(([formattedTime, counts]) => ({
    timestamp: formattedTime,
    formattedTime,
    count: counts.total,
    games: counts.games,
    couponsEarned: counts.couponsEarned,
    couponsRedeemed: counts.couponsRedeemed
  }));

  const campaignCounts: Record<string, number> = {};
  rawEvents.forEach(e => {
    const camp = e.campaign || 'Direct / Unspecified';
    campaignCounts[camp] = (campaignCounts[camp] || 0) + 1;
  });

  const campaignColors = ['#f97316', '#3b82f6', '#10b981', '#8b5cf6', '#ec4899', '#eab308'];
  const campaignDistribution = Object.entries(campaignCounts).map(([campaign, count], index) => ({
    campaign,
    count,
    percentage: totalEvents > 0 ? Number(((count / totalEvents) * 100).toFixed(1)) : 0,
    color: campaignColors[index % campaignColors.length]
  })).sort((a, b) => b.count - a.count);

  const redemptionRate = rewardsEarned > 0 ? (couponsRedeemed / rewardsEarned) * 100 : 0;

  return {
    kpis: {
      totalEvents,
      totalUniqueSessions: uniqueSessions,
      totalCouponsEarned: rewardsEarned,
      totalCouponsRedeemed: couponsRedeemed,
      redemptionRate: Number(redemptionRate.toFixed(1))
    },
    websiteKPIs,
    dailyRunKPIs,
    crossJourneyKPIs,
    sourcePerformance,
    eventFrequency,
    volumeOverTime,
    campaignDistribution
  };
}

// -------------------------------------------------------------
// API Endpoints
// -------------------------------------------------------------

app.get('/api/health', (req, res) => {
  const isSupabaseConfigured = !!(process.env.SUPABASE_URL && process.env.SUPABASE_SERVICE_ROLE_KEY);
  res.json({
    status: 'ok',
    timestamp: new Date().toISOString(),
    isSupabaseConfigured,
    supabaseUrlProvided: !!process.env.SUPABASE_URL
  });
});

// GET /api/rewards/schema.sql - Output copyable SQL DDL
app.get('/api/rewards/schema.sql', (req, res) => {
  res.type('text/plain').send(SQL_SCHEMA);
});

// GET /api/analytics/summary - Aggregated summary for analytics dashboard
app.get('/api/analytics/summary', async (req, res) => {
  const client = getSupabaseClient();
  const campaignFilter = req.query.campaign as string;

  let rawEvents: AnalyticsRow[] = [];
  let isSupabaseConfigured = false;
  let isSupabaseConnected = false;
  let dataSource: 'supabase' | 'simulated_fallback' = 'simulated_fallback';
  let errorMessage: string | null = null;

  if (client) {
    isSupabaseConfigured = true;
    try {
      let query = client
        .from('analytics_events')
        .select('*')
        .order('created_at', { ascending: false })
        .limit(1000);

      if (campaignFilter && campaignFilter !== 'all') {
        query = query.eq('campaign', campaignFilter);
      }

      const { data, error } = await query;
      if (!error && data && data.length > 0) {
        rawEvents = data as AnalyticsRow[];
        isSupabaseConnected = true;
        dataSource = 'supabase';
      } else if (error) {
        errorMessage = error.message;
        rawEvents = inMemoryEvents;
      } else {
        isSupabaseConnected = true;
        dataSource = 'supabase';
        rawEvents = [];
      }
    } catch (err: any) {
      errorMessage = err.message;
      rawEvents = inMemoryEvents;
    }
  } else {
    rawEvents = inMemoryEvents;
  }

  if (campaignFilter && campaignFilter !== 'all' && dataSource === 'simulated_fallback') {
    rawEvents = rawEvents.filter(e => e.campaign === campaignFilter);
  }

  const aggregated = computeAnalyticsSummary(rawEvents);

  res.json({
    success: true,
    dataSource,
    isSupabaseConfigured,
    isSupabaseConnected,
    isRevenueAttributionPending: true,
    statusNote: 'WhatsApp Order Intent tracked; revenue attribution pending confirmed customer pickup/delivery.',
    error: errorMessage,
    lastUpdated: new Date().toISOString(),
    ...aggregated,
    rawEvents: rawEvents.slice(0, 100)
  });
});

// GET /api/analytics/events - Raw events
app.get('/api/analytics/events', async (req, res) => {
  const client = getSupabaseClient();
  const limit = Math.min(parseInt(req.query.limit as string) || 200, 1000);

  if (client) {
    try {
      const { data, error } = await client
        .from('analytics_events')
        .select('*')
        .order('created_at', { ascending: false })
        .limit(limit);

      if (!error && data) {
        return res.json({
          success: true,
          dataSource: 'supabase',
          isSupabaseConfigured: true,
          isSupabaseConnected: true,
          events: data
        });
      }
    } catch {}
  }

  return res.json({
    success: true,
    dataSource: 'simulated_fallback',
    isSupabaseConfigured: false,
    isSupabaseConnected: false,
    events: inMemoryEvents.slice(0, limit)
  });
});

// POST /api/analytics/events - Insert event with anonymous identity model & safety
app.post('/api/analytics/events', async (req, res) => {
  const {
    visitor_id,
    session_id,
    campaign,
    event,
    event_category,
    source,
    medium,
    referrer,
    page,
    path,
    timestamp,
    game_version,
    game_mode,
    data,
    player_id
  } = req.body;

  if (!event) {
    return res.status(400).json({ error: 'Field "event" is required.' });
  }

  // Derive event_category if not explicitly supplied
  let cleanCategory = event_category;
  if (!cleanCategory) {
    if (['session_started', 'landing_page_viewed'].includes(event)) cleanCategory = 'acquisition';
    else if (['page_viewed', 'section_viewed', 'menu_viewed', 'product_viewed', 'cta_clicked', 'cart_viewed', 'add_to_cart', 'remove_from_cart'].includes(event)) cleanCategory = 'website';
    else if (['order_cta_clicked', 'whatsapp_order_opened', 'coupon_entered', 'coupon_validated', 'coupon_applied'].includes(event)) cleanCategory = 'commerce';
    else if (['daily_run_section_viewed', 'daily_run_cta_clicked', 'post_order_daily_run_cta_clicked', 'game_started', 'game_played', 'game_completed', 'challenge_completed', 'cyberwrap_launch_clicked'].includes(event)) cleanCategory = 'daily_run';
    else if (['reward_earned', 'reward_viewed', 'reward_copied', 'coupon_earned', 'coupon_redeemed'].includes(event)) cleanCategory = 'reward';
    else if (['scroll_depth', 'section_visibility', 'element_clicked', 'dead_click', 'rage_click'].includes(event)) cleanCategory = 'ux';
    else cleanCategory = 'website';
  }

  // Normalize identities
  const cleanSessionId = session_id || `sess_${Date.now()}_${Math.floor(Math.random() * 8999 + 1000)}`;
  const cleanVisitorId = visitor_id || `vis_${cleanSessionId.replace(/^sess_/, '')}`;

  // Sanitize PII from data
  const sanitizedData: Record<string, any> = {};
  if (data && typeof data === 'object') {
    const piiKeys = ['name', 'phone', 'address', 'message', 'notes', 'email'];
    for (const [k, v] of Object.entries(data)) {
      if (!piiKeys.some(pii => k.toLowerCase().includes(pii))) {
        sanitizedData[k] = v;
      }
    }
  }

  const nowIso = new Date().toISOString();
  const newEvent: AnalyticsRow = {
    id: Date.now(),
    visitor_id: cleanVisitorId,
    session_id: cleanSessionId,
    player_id: player_id || null,
    campaign: campaign || 'dailybread-cyberwrap',
    event,
    event_category: cleanCategory,
    source: source || 'website',
    medium: medium || 'direct',
    referrer: referrer || null,
    page: page || '/',
    path: path || '/',
    timestamp: timestamp || Date.now(),
    game_version: game_version || 'web-v1.4.2',
    game_mode: game_mode || null,
    data: sanitizedData,
    created_at: nowIso
  };

  // Upsert in-memory visitor
  const existingVis = inMemoryVisitors.get(cleanVisitorId);
  if (!existingVis) {
    inMemoryVisitors.set(cleanVisitorId, {
      visitor_id: cleanVisitorId,
      first_seen_at: nowIso,
      last_seen_at: nowIso,
      first_source: newEvent.source,
      first_medium: newEvent.medium,
      first_campaign: newEvent.campaign,
      first_referrer: newEvent.referrer,
      first_landing_page: newEvent.page,
      created_at: nowIso
    });
  } else {
    existingVis.last_seen_at = nowIso;
  }

  // Upsert in-memory session
  const existingSess = inMemorySessions.get(cleanSessionId);
  if (!existingSess) {
    inMemorySessions.set(cleanSessionId, {
      session_id: cleanSessionId,
      visitor_id: cleanVisitorId,
      started_at: nowIso,
      landing_page: newEvent.page,
      source: newEvent.source,
      medium: newEvent.medium,
      campaign: newEvent.campaign,
      referrer: newEvent.referrer,
      created_at: nowIso
    });
  }

  const client = getSupabaseClient();
  if (client) {
    try {
      // First attempt inserting full new schema row into analytics_events
      const fullInsertPayload = {
        session_id: newEvent.session_id,
        campaign: newEvent.campaign,
        event: newEvent.event,
        timestamp: newEvent.timestamp,
        game_version: newEvent.game_version,
        data: newEvent.data,
        player_id: newEvent.player_id,
        visitor_id: newEvent.visitor_id,
        event_category: newEvent.event_category,
        source: newEvent.source,
        medium: newEvent.medium,
        referrer: newEvent.referrer,
        page: newEvent.page,
        path: newEvent.path
      };

      const { data: inserted, error } = await client
        .from('analytics_events')
        .insert([fullInsertPayload])
        .select();

      if (!error && inserted && inserted.length > 0) {
        // Asynchronously attempt to record visitor and session in Supabase (fire and forget)
        (async () => {
          try {
            await client.from('analytics_visitors').upsert({
              visitor_id: cleanVisitorId,
              last_seen_at: nowIso,
              first_source: newEvent.source,
              first_campaign: newEvent.campaign
            });
          } catch {
            // Ignored if table not yet migrated
          }
          try {
            await client.from('analytics_sessions').upsert({
              session_id: cleanSessionId,
              visitor_id: cleanVisitorId,
              started_at: nowIso,
              source: newEvent.source,
              campaign: newEvent.campaign
            });
          } catch {
            // Ignored if table not yet migrated
          }
        })();

        return res.status(201).json({
          success: true,
          savedTo: 'supabase',
          event: inserted[0]
        });
      }

      // If error was due to missing columns in table, fallback to inserting baseline columns
      if (error) {
        const { data: fallbackInserted, error: fallbackError } = await client
          .from('analytics_events')
          .insert([{
            session_id: newEvent.session_id,
            campaign: newEvent.campaign,
            event: newEvent.event,
            timestamp: newEvent.timestamp,
            game_version: newEvent.game_version || 'v1.4.2',
            data: newEvent.data,
            player_id: newEvent.player_id
          }])
          .select();

        if (!fallbackError && fallbackInserted && fallbackInserted.length > 0) {
          return res.status(201).json({
            success: true,
            savedTo: 'supabase_baseline',
            event: fallbackInserted[0]
          });
        }
      }
    } catch {}
  }

  inMemoryEvents.unshift(newEvent);
  if (inMemoryEvents.length > 1000) inMemoryEvents.pop();

  res.status(201).json({
    success: true,
    savedTo: 'simulated_memory',
    event: newEvent
  });
});

// -------------------------------------------------------------
// Cyberwrap Rewards & Admin Routes
// -------------------------------------------------------------

// GET /api/admin/rewards/overview - Relational metrics & overview for Admin
app.get('/api/admin/rewards/overview', async (req, res) => {
  const client = getSupabaseClient();
  let dataSource: 'supabase' | 'simulated_fallback' = 'simulated_fallback';
  let isSupabaseConfigured = Boolean(process.env.SUPABASE_URL && process.env.SUPABASE_SERVICE_ROLE_KEY);
  let isSupabaseConnected = false;
  let errorMsg: string | null = null;

  let coupons: CyberwrapCouponRow[] = [];
  let players: CyberwrapRewardRow[] = [];
  let claims: CyberwrapRewardClaimRow[] = [];

  const now = new Date();
  const nowMs = now.getTime();

  if (client) {
    try {
      const [couponsRes, rewardsRes, claimsRes] = await Promise.all([
        client.from('cyberwrap_coupons').select('*').order('created_at', { ascending: false }).limit(500),
        client.from('cyberwrap_rewards').select('*').order('cumulative_score', { ascending: false }).limit(500),
        client.from('cyberwrap_reward_claims').select('*').order('created_at', { ascending: false }).limit(500),
      ]);

      if (!couponsRes.error && !rewardsRes.error && !claimsRes.error) {
        coupons = (couponsRes.data || []) as CyberwrapCouponRow[];
        players = (rewardsRes.data || []) as CyberwrapRewardRow[];
        claims = (claimsRes.data || []) as CyberwrapRewardClaimRow[];
        isSupabaseConnected = true;
        dataSource = 'supabase';
      } else {
        errorMsg = couponsRes.error?.message || rewardsRes.error?.message || claimsRes.error?.message || 'Supabase read error';
        coupons = inMemoryCoupons;
        players = inMemoryPlayers;
        claims = inMemoryClaims;
      }
    } catch (err: any) {
      errorMsg = err.message || 'Supabase connection error';
      coupons = inMemoryCoupons;
      players = inMemoryPlayers;
      claims = inMemoryClaims;
    }
  } else {
    coupons = inMemoryCoupons;
    players = inMemoryPlayers;
    claims = inMemoryClaims;
  }

  // Calculate Metrics strictly according to specifications
  // 1. Total Coupons Issued: Count rows from cyberwrap_coupons including active, expired and redeemed coupons
  const totalCouponsIssued = coupons.length;

  // Server-side time-based expiration logic:
  // An active coupon whose expires_at <= now() must be displayed as expired.
  const processedCoupons = coupons.map(c => {
    let computedStatus = c.status;
    if (c.status === 'active' && new Date(c.expires_at).getTime() <= nowMs) {
      computedStatus = 'expired';
    }
    return {
      ...c,
      status: computedStatus
    };
  });

  // 2. Active Coupons: status = 'active' AND expires_at > now()
  const totalCouponsActive = processedCoupons.filter(c => c.status === 'active').length;

  // 3. Redeemed Coupons: status = 'redeemed'
  const totalCouponsRedeemed = processedCoupons.filter(c => c.status === 'redeemed').length;

  // 4. Expired Coupons: status = 'expired' OR (status = 'active' AND expires_at <= now())
  const totalCouponsExpired = processedCoupons.filter(c => c.status === 'expired').length;

  // 5. Coupon Redemption Rate: (totalCouponsRedeemed / totalCouponsIssued) * 100
  const redemptionRatePercent = totalCouponsIssued > 0 
    ? Number(((totalCouponsRedeemed / totalCouponsIssued) * 100).toFixed(1)) 
    : 0;

  // 6. Active Reward Cycles: Count players in cyberwrap_rewards where cycle_expires_at > now()
  const activeRewardCycles = players.filter(p => new Date(p.cycle_expires_at).getTime() > nowMs).length;

  // 7. Total Participating Players: Count rows in cyberwrap_rewards
  const totalActivePlayers = players.length;

  // 8. Total Claimed Score: Calculate from cyberwrap_reward_claims using actual credited score
  const totalScoreClaimed = claims.reduce((acc, curr) => acc + (Number(curr.credited_amount) || Number(curr.score_amount) || 0), 0);
  const totalCreditedAmount = totalScoreClaimed;

  // 9. Total Claims: Count rows in cyberwrap_reward_claims
  const totalRewardClaims = claims.length;

  // 10. Average Claim: total credited_amount / total claims (0 if no claims)
  const avgScorePerClaim = totalRewardClaims > 0 ? Math.round(totalScoreClaimed / totalRewardClaims) : 0;

  // Build relational player objects
  const playersWithRelations = players.map(p => ({
    ...p,
    coupons: processedCoupons.filter(c => c.player_id === p.player_id),
    claims: claims.filter(c => c.player_id === p.player_id),
  }));

  res.json({
    success: true,
    dataSource,
    isSupabaseConfigured,
    isSupabaseConnected,
    error: errorMsg,
    serverTime: now.toISOString(),
    lastUpdated: now.toISOString(),
    metrics: {
      totalCouponsIssued,
      totalCouponsActive,
      totalCouponsRedeemed,
      totalCouponsExpired,
      redemptionRatePercent,
      activeRewardCycles,
      totalActivePlayers,
      totalScoreClaimed,
      totalCreditedAmount,
      totalRewardClaims,
      avgScorePerClaim
    },
    recentCoupons: processedCoupons,
    topPlayers: playersWithRelations,
    recentClaims: claims.slice(0, 100)
  });
});

// GET /api/admin/rewards/coupons - List coupons with optional status filter & search
app.get('/api/admin/rewards/coupons', async (req, res) => {
  const status = req.query.status as string;
  const search = (req.query.search as string || '').toLowerCase();
  const client = getSupabaseClient();
  const nowMs = Date.now();

  let list = inMemoryCoupons;
  let dataSource = 'simulated_fallback';

  if (client) {
    try {
      let query = client.from('cyberwrap_coupons').select('*').order('created_at', { ascending: false }).limit(500);
      const { data, error } = await query;
      if (!error && data) {
        list = data as CyberwrapCouponRow[];
        dataSource = 'supabase';
      }
    } catch {}
  }

  // Dynamically compute expiration status using server time
  let processed = list.map(c => {
    let computedStatus = c.status;
    if (c.status === 'active' && new Date(c.expires_at).getTime() <= nowMs) {
      computedStatus = 'expired';
    }
    return { ...c, status: computedStatus };
  });

  if (status && status !== 'all') {
    processed = processed.filter(c => c.status === status);
  }

  if (search) {
    processed = processed.filter(c => 
      c.code_hash.toLowerCase().includes(search) || 
      c.player_id.toLowerCase().includes(search)
    );
  }

  res.json({
    success: true,
    dataSource,
    total: processed.length,
    coupons: processed
  });
});

// PATCH /api/admin/rewards/coupons/:id/status - Manually update coupon status
app.patch('/api/admin/rewards/coupons/:id/status', async (req, res) => {
  const { id } = req.params;
  const { status } = req.body;

  if (!['active', 'redeemed', 'expired'].includes(status)) {
    return res.status(400).json({ error: 'Invalid coupon status. Allowed values: active, redeemed, expired.' });
  }

  const client = getSupabaseClient();
  const now = new Date().toISOString();

  if (client) {
    try {
      const updateData: any = { status };
      if (status === 'redeemed') updateData.redeemed_at = now;

      const isUuid = isValidUuid(id);
      let query = client.from('cyberwrap_coupons').update(updateData);
      if (isUuid) {
        query = query.eq('id', id);
      } else {
        query = query.eq('code_hash', id);
      }

      const { data, error } = await query.select();

      if (!error && data && data.length > 0) {
        return res.json({
          success: true,
          coupon: data[0],
          message: `Coupon status updated to ${status} in Supabase.`
        });
      }
    } catch (err: any) {
      console.warn('Supabase coupon status update failed:', err);
    }
  }

  // Fallback update
  const coupon = inMemoryCoupons.find(c => c.id === id || c.code_hash === id);
  if (!coupon) {
    return res.status(404).json({ error: 'Coupon not found.' });
  }

  coupon.status = status;
  if (status === 'redeemed') coupon.redeemed_at = now;

  res.json({
    success: true,
    coupon,
    message: `Coupon status updated to ${status} in local state.`
  });
});

// POST /api/rewards/claim-score - User flow: Submit game score, update rewards, trigger coupons (200 pts threshold)
app.post('/api/rewards/claim-score', async (req, res) => {
  const { player_id, session_id, game_id, score_amount, game_version } = req.body;

  if (!player_id || score_amount === undefined || score_amount === null) {
    return res.status(400).json({ error: 'player_id and score_amount are required.' });
  }

  const numScore = parseInt(score_amount, 10);
  if (isNaN(numScore) || numScore <= 0) {
    return res.status(400).json({ error: 'score_amount must be a positive integer.' });
  }

  const now = new Date().toISOString();
  const nowMs = Date.now();
  const client = getSupabaseClient();

  // Ensure valid UUIDs for PostgreSQL schema compliance
  const playerUuid = ensureUuid(player_id);
  const claimUuid = crypto.randomUUID();
  const gameUuid = ensureUuid(game_id);
  const rewardUuid = crypto.randomUUID();
  const couponUuid = crypto.randomUUID();
  const sessId = session_id || `sess_${Math.floor(Math.random() * 8999 + 1000)}`;

  // Duplicate Protection: Submitting the same game_id twice must NOT credit score again
  if (game_id) {
    let duplicateClaim: CyberwrapRewardClaimRow | undefined;
    if (client) {
      try {
        const { data: existingClaim } = await client
          .from('cyberwrap_reward_claims')
          .select('*')
          .eq('game_id', gameUuid)
          .maybeSingle();
        if (existingClaim) duplicateClaim = existingClaim as CyberwrapRewardClaimRow;
      } catch {}
    }
    if (!duplicateClaim) {
      duplicateClaim = inMemoryClaims.find(c => c.game_id === gameUuid || c.game_id === game_id);
    }
    if (duplicateClaim) {
      return res.status(409).json({
        success: false,
        duplicate: true,
        error: 'Duplicate submission: This game score has already been claimed.',
        claim: duplicateClaim
      });
    }
  }

  let playerReward: CyberwrapRewardRow | undefined;
  let existingRewardId = rewardUuid;

  if (client) {
    try {
      const { data: existingPlayer } = await client
        .from('cyberwrap_rewards')
        .select('*')
        .eq('player_id', playerUuid)
        .maybeSingle();

      if (existingPlayer) {
        playerReward = existingPlayer as CyberwrapRewardRow;
        existingRewardId = existingPlayer.id;
      }
    } catch (err) {
      console.warn('Supabase player reward lookup error:', err);
    }
  }

  if (!playerReward) {
    playerReward = inMemoryPlayers.find(p => p.player_id === playerUuid || p.player_id === player_id);
  }

  // 7-day cycle duration in milliseconds
  const CYCLE_DURATION_MS = 7 * 24 * 60 * 60 * 1000;

  if (playerReward) {
    // 7-Day Cycle Check: If current cycle has expired, reset cumulative score and coupons count
    const cycleExpiresMs = new Date(playerReward.cycle_expires_at).getTime();
    if (cycleExpiresMs <= nowMs) {
      playerReward.cumulative_score = 0;
      playerReward.coupons_earned_in_cycle = 0;
      playerReward.cycle_started_at = now;
      playerReward.cycle_expires_at = new Date(nowMs + CYCLE_DURATION_MS).toISOString();
      playerReward.reward_status = 'active';
    }
  } else {
    // New player reward cycle initialization (7-day cycle)
    playerReward = {
      id: existingRewardId,
      player_id: playerUuid,
      cumulative_score: 0,
      cycle_started_at: now,
      cycle_expires_at: new Date(nowMs + CYCLE_DURATION_MS).toISOString(),
      coupons_earned_in_cycle: 0,
      reward_status: 'active',
      created_at: now,
      updated_at: now
    };
    inMemoryPlayers.push(playerReward);
  }

  // -------------------------------------------------------------
  // Approved CyberWrap Reward Logic:
  // current cumulative score + completed session score = new cumulative score
  // When cumulative_score >= 200 AND coupons_earned_in_cycle < 2:
  // 1. Generate one unique 20% coupon.
  // 2. Coupon expires exactly 7 days after generated_at.
  // 3. Increment coupons_earned_in_cycle.
  // 4. Subtract 200 from cumulative_score.
  // 5. Carry any remaining points forward.
  // -------------------------------------------------------------
  const REWARD_THRESHOLD_PTS = 200;
  const MAX_COUPONS_PER_CYCLE = 2;
  const currentCumulative = Number(playerReward.cumulative_score) || 0;
  let remainingCumulative = currentCumulative + numScore;
  let couponsEarnedInCycle = Number(playerReward.coupons_earned_in_cycle) || 0;
  const newlyGeneratedCoupons: CyberwrapCouponRow[] = [];
  let milestoneReached = false;

  // Issue up to MAX_COUPONS_PER_CYCLE (2) coupons when score reaches threshold multiples
  while (remainingCumulative >= REWARD_THRESHOLD_PTS && couponsEarnedInCycle < MAX_COUPONS_PER_CYCLE) {
    milestoneReached = true;
    couponsEarnedInCycle += 1;
    remainingCumulative -= REWARD_THRESHOLD_PTS; // Deduct exactly 200 pts per issued coupon

    const currentCouponUuid = crypto.randomUUID();
    const couponSuffix = Math.floor(Math.random() * 8999 + 1000);
    const code = `SHAWARMA-20-${couponSuffix}`;
    const couponExpiresAt = new Date(nowMs + CYCLE_DURATION_MS).toISOString(); // Exactly 7 days

    const createdCoupon: CyberwrapCouponRow = {
      id: currentCouponUuid,
      player_id: playerUuid,
      reward_id: playerReward.id,
      code_hash: code,
      discount_percent: 20,
      status: 'active',
      generated_at: now,
      expires_at: couponExpiresAt,
      redeemed_at: null,
      created_at: now
    };

    newlyGeneratedCoupons.push(createdCoupon);
    inMemoryCoupons.unshift(createdCoupon);

    inMemoryEvents.unshift({
      id: Date.now() + newlyGeneratedCoupons.length,
      session_id: sessId,
      campaign: 'Summer Shawarma Splash',
      event: 'coupon_earned',
      timestamp: Date.now(),
      game_version: game_version || 'v1.4.2',
      data: { 
        coupon_code: code, 
        discount: '20%', 
        score: numScore, 
        cumulative_remainder: remainingCumulative,
        coupons_in_cycle: couponsEarnedInCycle
      },
      created_at: now,
      player_id: playerUuid
    });
  }

  // Update authoritative reward state
  playerReward.cumulative_score = remainingCumulative;
  playerReward.coupons_earned_in_cycle = couponsEarnedInCycle;
  playerReward.reward_status = couponsEarnedInCycle >= MAX_COUPONS_PER_CYCLE ? 'cycle_completed' : 'active';
  playerReward.updated_at = now;

  const primaryCoupon = newlyGeneratedCoupons[0] || null;

  // Create Claim Record
  const newClaim: CyberwrapRewardClaimRow = {
    id: claimUuid,
    player_id: playerUuid,
    session_id: sessId,
    game_id: gameUuid,
    score_amount: numScore,
    credited_amount: numScore,
    coupon_id: primaryCoupon ? primaryCoupon.id : null,
    created_at: now
  };
  inMemoryClaims.unshift(newClaim);

  // Sync with Supabase
  if (client) {
    try {
      // 1. Upsert reward cycle
      const { data: upsertedReward } = await client
        .from('cyberwrap_rewards')
        .upsert({
          player_id: playerUuid,
          cumulative_score: playerReward.cumulative_score,
          cycle_started_at: playerReward.cycle_started_at,
          cycle_expires_at: playerReward.cycle_expires_at,
          coupons_earned_in_cycle: playerReward.coupons_earned_in_cycle,
          reward_status: playerReward.reward_status,
          updated_at: now
        }, { onConflict: 'player_id' })
        .select();

      const realRewardId = (upsertedReward && upsertedReward[0]?.id) || playerReward.id;

      // 2. Insert any newly generated coupons
      let realCouponId: string | null = null;
      if (newlyGeneratedCoupons.length > 0) {
        const couponsToInsert = newlyGeneratedCoupons.map(c => ({
          id: c.id,
          player_id: playerUuid,
          reward_id: realRewardId,
          code_hash: c.code_hash,
          discount_percent: 20,
          status: 'active',
          generated_at: c.generated_at,
          expires_at: c.expires_at
        }));

        const { data: insertedCoupons } = await client
          .from('cyberwrap_coupons')
          .insert(couponsToInsert)
          .select();

        realCouponId = (insertedCoupons && insertedCoupons[0]?.id) || primaryCoupon?.id || null;
      }

      // 3. Insert claim
      await client
        .from('cyberwrap_reward_claims')
        .insert([{
          id: claimUuid,
          player_id: playerUuid,
          session_id: sessId,
          game_id: gameUuid,
          score_amount: numScore,
          credited_amount: numScore,
          coupon_id: realCouponId
        }]);

      // 4. Log events
      const eventsToInsert: Array<{
        session_id: string;
        campaign: string;
        event: string;
        timestamp: number;
        game_version: string;
        data: Record<string, any>;
        player_id: string;
      }> = [
        {
          session_id: sessId,
          campaign: 'Summer Shawarma Splash',
          event: 'game_played',
          timestamp: Date.now(),
          game_version: game_version || 'v1.4.2',
          data: { score: numScore, player_id: playerUuid, game_id: gameUuid, cumulative_score: playerReward.cumulative_score },
          player_id: playerUuid
        }
      ];

      newlyGeneratedCoupons.forEach((couponItem) => {
        eventsToInsert.push({
          session_id: sessId,
          campaign: 'Summer Shawarma Splash',
          event: 'coupon_earned',
          timestamp: Date.now(),
          game_version: game_version || 'v1.4.2',
          data: { 
            coupon_id: couponItem.id,
            coupon_code: couponItem.code_hash, 
            discount: '20%', 
            score: numScore, 
            game_id: gameUuid,
            player_id: playerUuid
          },
          player_id: playerUuid
        });
      });

      await client
        .from('analytics_events')
        .insert(eventsToInsert);
    } catch (e) {
      console.warn('Supabase claim sync exception, stored in local memory:', e);
    }
  }

  res.status(201).json({
    success: true,
    claim: newClaim,
    reward: playerReward,
    newCoupon: primaryCoupon,
    newCoupons: newlyGeneratedCoupons,
    milestoneReached,
    message: milestoneReached
      ? `🎉 Score +${numScore} credited! ${newlyGeneratedCoupons.length} coupon(s) unlocked! Remaining balance: ${playerReward.cumulative_score} / 200 pts.`
      : `Score +${numScore} credited to reward cycle (${playerReward.cumulative_score} / 200 pts towards 20% coupon).`
  });
});

// GET /api/rewards/player/:player_id - Player-facing API to retrieve reward cycle and available coupons
app.get('/api/rewards/player/:player_id', async (req, res) => {
  const { player_id } = req.params;
  const playerUuid = ensureUuid(player_id);
  const client = getSupabaseClient();
  const nowMs = Date.now();

  let playerReward: CyberwrapRewardRow | undefined;
  let playerCoupons: CyberwrapCouponRow[] = [];
  let playerClaims: CyberwrapRewardClaimRow[] = [];

  if (client) {
    try {
      const [rRes, cRes, clRes] = await Promise.all([
        client.from('cyberwrap_rewards').select('*').eq('player_id', playerUuid).maybeSingle(),
        client.from('cyberwrap_coupons').select('*').eq('player_id', playerUuid).order('created_at', { ascending: false }),
        client.from('cyberwrap_reward_claims').select('*').eq('player_id', playerUuid).order('created_at', { ascending: false })
      ]);

      if (rRes.data) playerReward = rRes.data as CyberwrapRewardRow;
      if (cRes.data) playerCoupons = cRes.data as CyberwrapCouponRow[];
      if (clRes.data) playerClaims = clRes.data as CyberwrapRewardClaimRow[];
    } catch (err) {
      console.warn('Supabase player fetch error:', err);
    }
  }

  if (!playerReward) {
    playerReward = inMemoryPlayers.find(p => p.player_id === playerUuid || p.player_id === player_id);
  }
  if (playerCoupons.length === 0) {
    playerCoupons = inMemoryCoupons.filter(c => c.player_id === playerUuid || c.player_id === player_id);
  }
  if (playerClaims.length === 0) {
    playerClaims = inMemoryClaims.filter(c => c.player_id === playerUuid || c.player_id === player_id);
  }

  // Calculate dynamic coupon expiration statuses using server time
  const processedCoupons = playerCoupons.map(c => {
    let computedStatus = c.status;
    if (c.status === 'active' && new Date(c.expires_at).getTime() <= nowMs) {
      computedStatus = 'expired';
    }
    return { ...c, status: computedStatus };
  });

  const activeCoupons = processedCoupons.filter(c => c.status === 'active');
  const redeemedCoupons = processedCoupons.filter(c => c.status === 'redeemed');
  const expiredCoupons = processedCoupons.filter(c => c.status === 'expired');

  res.json({
    success: true,
    player_id: playerUuid,
    reward: playerReward || null,
    cumulative_score: playerReward ? playerReward.cumulative_score : 0,
    coupons_earned_in_cycle: playerReward ? playerReward.coupons_earned_in_cycle : 0,
    cycle_expires_at: playerReward ? playerReward.cycle_expires_at : null,
    coupons: processedCoupons,
    activeCoupons,
    redeemedCoupons,
    expiredCoupons,
    claims: playerClaims
  });
});

// POST /api/admin/rewards/seed - Seed demo data strictly adhering to 200 pts threshold and 7-day cycles
app.post('/api/admin/rewards/seed', async (req, res) => {
  const count = Math.min(parseInt(req.body.count, 10) || 5, 20);
  const now = new Date();
  const nowMs = now.getTime();
  const CYCLE_DURATION_MS = 7 * 24 * 60 * 60 * 1000;

  const demoPlayers = [
    { id: '11111111-1111-4111-a111-111111111111', name: 'Alain Mbarga (Top Scorer)', baseScore: 265, games: [75, 60, 80, 50] },
    { id: '22222222-2222-4222-a222-222222222222', name: 'Sandra Eto’o', baseScore: 185, games: [95, 90] },
    { id: '33333333-3333-4333-a333-333333333333', name: 'Junior Nsangou', baseScore: 140, games: [70, 70] },
    { id: '44444444-4444-4444-a444-444444444444', name: 'Chantal Biya', baseScore: 230, games: [120, 110] },
    { id: '55555555-5555-4555-a555-555555555555', name: 'Cedric Ngannou', baseScore: 65, games: [65] }
  ].slice(0, count);

  inMemoryPlayers = [];
  inMemoryCoupons = [];
  inMemoryClaims = [];

  for (const p of demoPlayers) {
    const rewardId = crypto.randomUUID();
    let cumulative = 0;
    let couponsEarned = 0;

    const rewardRow: CyberwrapRewardRow = {
      id: rewardId,
      player_id: p.id,
      playerName: p.name,
      cumulative_score: 0,
      cycle_started_at: new Date(nowMs - 2 * 24 * 60 * 60 * 1000).toISOString(),
      cycle_expires_at: new Date(nowMs + 5 * 24 * 60 * 60 * 1000).toISOString(),
      coupons_earned_in_cycle: 0,
      reward_status: 'in_progress',
      created_at: new Date(nowMs - 2 * 24 * 60 * 60 * 1000).toISOString(),
      updated_at: now.toISOString()
    };

    for (let i = 0; i < p.games.length; i++) {
      const score = p.games[i];
      const claimId = crypto.randomUUID();
      const gameId = crypto.randomUUID();
      const claimTime = new Date(nowMs - (p.games.length - i) * 6 * 60 * 60 * 1000).toISOString();
      let couponId: string | null = null;

      const newCumulative = cumulative + score;
      if (newCumulative >= 200 && couponsEarned < 2) {
        couponsEarned += 1;
        cumulative = newCumulative - 200;
        couponId = crypto.randomUUID();

        const couponRow: CyberwrapCouponRow = {
          id: couponId,
          player_id: p.id,
          reward_id: rewardId,
          code_hash: `SHAWARMA-20-${Math.floor(1000 + Math.random() * 8999)}`,
          discount_percent: 20,
          status: i === 0 && couponsEarned === 1 ? 'redeemed' : 'active',
          generated_at: claimTime,
          expires_at: new Date(new Date(claimTime).getTime() + CYCLE_DURATION_MS).toISOString(),
          redeemed_at: i === 0 && couponsEarned === 1 ? now.toISOString() : null,
          created_at: claimTime
        };
        inMemoryCoupons.push(couponRow);
      } else {
        cumulative = newCumulative;
      }

      inMemoryClaims.push({
        id: claimId,
        player_id: p.id,
        session_id: `sess_seed_${i + 1}`,
        game_id: gameId,
        score_amount: score,
        credited_amount: score,
        coupon_id: couponId,
        created_at: claimTime
      });
    }

    rewardRow.cumulative_score = cumulative;
    rewardRow.coupons_earned_in_cycle = couponsEarned;
    rewardRow.reward_status = couponsEarned >= 2 ? 'cycle_completed' : 'in_progress';
    inMemoryPlayers.push(rewardRow);
  }

  res.json({
    success: true,
    message: `Successfully seeded ${inMemoryPlayers.length} players, ${inMemoryCoupons.length} 20% coupons, and ${inMemoryClaims.length} claims.`,
    seededPlayers: inMemoryPlayers.length,
    seededCoupons: inMemoryCoupons.length,
    seededClaims: inMemoryClaims.length
  });
});

// POST /api/rewards/validate-coupon - Validate coupon without immediate redemption
app.post('/api/rewards/validate-coupon', async (req, res) => {
  const { code } = req.body;
  if (!code || typeof code !== 'string') {
    return res.status(400).json({ success: false, valid: false, error: 'Coupon code is required.' });
  }

  const query = code.trim();
  const now = new Date();
  const client = getSupabaseClient();

  if (client) {
    try {
      const isUuid = isValidUuid(query);
      let fetchQuery = client.from('cyberwrap_coupons').select('*');
      if (isUuid) {
        fetchQuery = fetchQuery.or(`code_hash.ilike.${query},id.eq.${query}`);
      } else {
        fetchQuery = fetchQuery.ilike('code_hash', query);
      }
      const { data, error } = await fetchQuery.maybeSingle();

      if (!error && data) {
        const isExpired = data.status === 'expired' || (data.status === 'active' && new Date(data.expires_at).getTime() <= now.getTime());
        if (isExpired) {
          return res.status(400).json({ success: false, valid: false, error: `Coupon ${data.code_hash} is expired.` });
        }
        if (data.status !== 'active') {
          return res.status(400).json({ success: false, valid: false, error: `Coupon is ${data.status.toUpperCase()} and cannot be used.` });
        }

        return res.json({
          success: true,
          valid: true,
          coupon: data,
          discountPercent: data.discount_percent || 20,
          message: `Valid coupon! ${data.discount_percent || 20}% discount applied to your order.`
        });
      }
    } catch (err) {
      console.warn('Supabase coupon validation error:', err);
    }
  }

  const coupon = inMemoryCoupons.find(c => c.code_hash.toLowerCase() === query.toLowerCase() || c.id === query);
  if (!coupon) {
    return res.status(404).json({ success: false, valid: false, error: 'Coupon code not recognized. Check the spelling or play CyberWrap Arcade to earn one!' });
  }

  const isExpired = coupon.status === 'expired' || (coupon.status === 'active' && new Date(coupon.expires_at).getTime() <= now.getTime());
  if (isExpired) {
    coupon.status = 'expired';
    return res.status(400).json({ success: false, valid: false, error: `Coupon ${coupon.code_hash} is expired.` });
  }
  if (coupon.status !== 'active') {
    return res.status(400).json({ success: false, valid: false, error: `Coupon is ${coupon.status.toUpperCase()} and cannot be used.` });
  }

  return res.json({
    success: true,
    valid: true,
    coupon,
    discountPercent: coupon.discount_percent || 20,
    message: `Valid coupon! ${coupon.discount_percent || 20}% discount applied to your order.`
  });
});

// POST /api/rewards/redeem-coupon - Redeem active voucher
app.post('/api/rewards/redeem-coupon', async (req, res) => {
  const { codeOrId, orderValueXaf } = req.body;

  if (!codeOrId) {
    return res.status(400).json({ error: 'codeOrId is required.' });
  }

  const query = codeOrId.trim();
  const now = new Date();
  const nowIso = now.toISOString();
  const client = getSupabaseClient();

  if (client) {
    try {
      const isUuid = isValidUuid(query);
      let fetchQuery = client.from('cyberwrap_coupons').select('*');
      if (isUuid) {
        fetchQuery = fetchQuery.or(`code_hash.eq.${query},id.eq.${query}`);
      } else {
        fetchQuery = fetchQuery.eq('code_hash', query);
      }
      const { data, error } = await fetchQuery.maybeSingle();

      if (!error && data) {
        // Enforce server-side expiration validation
        const isExpired = data.status === 'expired' || (data.status === 'active' && new Date(data.expires_at).getTime() <= now.getTime());
        if (isExpired) {
          return res.status(400).json({ error: `Coupon ${data.code_hash} is EXPIRED and cannot be redeemed.` });
        }
        if (data.status !== 'active') {
          return res.status(400).json({ error: `Coupon is currently ${data.status.toUpperCase()} and cannot be applied.` });
        }

        await client
          .from('cyberwrap_coupons')
          .update({ status: 'redeemed', redeemed_at: nowIso })
          .eq('id', data.id);

        const redeemSessId = `sess_redeem_${Math.floor(Math.random() * 9000 + 1000)}`;

        // Log coupon_redeemed analytics event
        try {
          await client
            .from('analytics_events')
            .insert([{
              session_id: redeemSessId,
              campaign: 'Summer Shawarma Splash',
              event: 'coupon_redeemed',
              timestamp: Date.now(),
              game_version: 'v1.4.2',
              data: {
                coupon_id: data.id,
                coupon_code: data.code_hash,
                discount: `${data.discount_percent}%`,
                order_value_xaf: orderValueXaf || 3500,
                player_id: data.player_id
              },
              player_id: data.player_id
            }]);
        } catch (eventErr) {
          console.warn('Supabase coupon_redeemed event logging error:', eventErr);
        }

        return res.json({
          success: true,
          coupon: { ...data, status: 'redeemed', redeemed_at: nowIso },
          discountPercent: data.discount_percent,
          message: `Voucher ${data.code_hash} successfully redeemed (-${data.discount_percent}% applied).`
        });
      }
    } catch (err: any) {
      console.warn('Supabase coupon redeem lookup failed:', err);
    }
  }

  const coupon = inMemoryCoupons.find(c => c.code_hash.toLowerCase() === query.toLowerCase() || c.id === query);
  if (!coupon) {
    return res.status(404).json({ error: 'Coupon code not found in registry.' });
  }

  const isExpired = coupon.status === 'expired' || (coupon.status === 'active' && new Date(coupon.expires_at).getTime() <= now.getTime());
  if (isExpired) {
    coupon.status = 'expired';
    return res.status(400).json({ error: `Coupon is EXPIRED and cannot be redeemed.` });
  }

  if (coupon.status !== 'active') {
    return res.status(400).json({ error: `Coupon is ${coupon.status.toUpperCase()} and cannot be redeemed.` });
  }

  coupon.status = 'redeemed';
  coupon.redeemed_at = nowIso;

  // Log redemption event
  inMemoryEvents.unshift({
    id: Date.now(),
    session_id: `sess_redeem_${Math.floor(Math.random() * 9000 + 1000)}`,
    campaign: 'Summer Shawarma Splash',
    event: 'coupon_redeemed',
    timestamp: Date.now(),
    game_version: 'v1.4.2',
    data: { coupon_code: coupon.code_hash, discount: `${coupon.discount_percent}%`, order_value_xaf: orderValueXaf || 3500 },
    created_at: nowIso,
    player_id: coupon.player_id
  });

  res.json({
    success: true,
    coupon,
    discountPercent: coupon.discount_percent,
    message: `Voucher ${coupon.code_hash} successfully redeemed (-${coupon.discount_percent}% applied).`
  });
});

// Fallback static route for 3D model smoothie.glb requests
app.get(['/smoothie.glb', '/public/smoothie.glb'], (req, res) => {
  const primaryPath = path.join(process.cwd(), 'public', 'smoothie.glb');
  const fallbackPath = path.join(process.cwd(), 'public', '3d_shawarma_sample-specimen-v1.glb');
  if (fs.existsSync(primaryPath)) {
    res.sendFile(primaryPath);
  } else if (fs.existsSync(fallbackPath)) {
    res.sendFile(fallbackPath);
  } else {
    res.status(404).send('3D Model not found');
  }
});

// -------------------------------------------------------------
// Vite Server Integration
// -------------------------------------------------------------
async function startServer() {
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
